apiVersion: v1
kind: Namespace
metadata:
  name: visualize
  labels:
    shared-gateway-access: "true"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: cymbal-topic-subscriber@k8s-demos-386513.iam.gserviceaccount.com
  name: visualize
  namespace: visualize
