apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: welcome-autoscale
  namespace: welcome
spec:
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 15
      policies:
      - type: Percent
        value: 80
        periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 10
        periodSeconds: 15
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: welcome-autoscale
  minReplicas: 1
  maxReplicas: 20
  metrics:
  - type: Object
    object:
      describedObject:
        kind: Service
        name: welcome-autoscale
      metric:
        name: "autoscaling.googleapis.com|gclb-capacity-utilization"
      target:
        averageValue: 80
        type: AverageValue