apiVersion: v1
kind: Namespace
metadata:
  name: welcome
  labels:
    shared-gateway-access: "true"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-autoscale
  namespace: welcome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: welcome-autoscale
  template:
    metadata:
      labels:
        app: welcome-autoscale
    spec:
      containers:
      - name: cymbal
        image:  europe-west4-docker.pkg.dev/k8s-demos-386513/cloudday/welcome:sayhi
        ports:
          - containerPort: 8080
        env:
        - name: PROJECT_ID
          value: "k8s-demos-386513"
        - name: TOPIC_NAME
          value: "cymbal-topic-local"
        - name: MESSAGE_INTERVAL
          value: "2"
      serviceAccountName: welcome

---
apiVersion: v1
kind: Service
metadata:
  name: welcome-autoscale
  namespace: welcome
  annotations:
    networking.gke.io/max-rate-per-endpoint: "5"
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http 
  selector:
    app: welcome-autoscale
  type: ClusterIP
---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: welcome-autoscale
  namespace: welcome
  labels:
    gateway: welcome-autoscale
spec:
  parentRefs:
  - name: welcome-autoscale
    namespace: gateway
  hostnames:
  - "cloudday.manasakandula.tech"
  rules:
  - backendRefs:
    - name: welcome-autoscale
      port: 8080