apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: welcome-autoscale
  namespace: welcome
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: welcome-autoscale
  minReplicas: 1
  maxReplicas: 20
  metrics:
  - type: Object
    object:
      describedObject:
        kind: Service
        name: welcome-autoscale
      metric:
        name: "autoscaling.googleapis.com|gclb-capacity-utilization"
      target:
        averageValue: 70
        type: AverageValue