steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker pull europe-west4-docker.pkg.dev/k8s-demos-386513/cloudday/welcome:latest || exit 0']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 
          'build', 
          '-t', 'europe-west4-docker.pkg.dev/k8s-demos-386513/cloudday/welcome',
          '--cache-from', 'europe-west4-docker.pkg.dev/k8s-demos-386513/cloudday/welcome',
          './webpage' 
        ]
images:
- 'europe-west4-docker.pkg.dev/k8s-demos-386513/cloudday/welcome'
options:
  logging: CLOUD_LOGGING_ONLY
