steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 
          'build', 
          '-t', 'europe-west4-docker.pkg.dev/k8s-demos-386513/cloudday/welcome:sayhi',
          './webpage' 
        ]
- name: "gcr.io/cloud-builders/docker"
  args: [
        'push', 
        'europe-west4-docker.pkg.dev/k8s-demos-386513/cloudday/welcome:sayhi'
        ]

- name: "gcr.io/cloud-builders/gke-deploy"
  args: [
        'run',
        '--filename=kubernetes/demo/1_deployment.yaml',
        '--location=europe-west4',
        '--cluster=autopilot-cluster'
       ]
options:
  logging: CLOUD_LOGGING_ONLY
