steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 
          'build', 
          '-t', 'europe-west4-docker.pkg.dev/k8s-demos-386513/cloudday/welcome:latest',
          './webpage' 
        ]
  id: Build_Container
- name: "gcr.io/cloud-builders/docker"
  args: [
        'push', 
        'europe-west4-docker.pkg.dev/k8s-demos-386513/cloudday/welcome:sayhi'
        ]
  id: Push_Container
- name: "gcr.io/cloud-builders/gke-deploy"
  args: [
        'run',
        '--filename=kubernetes/demo/1_deployment.yaml',
        '--location=europe-west4',
        '--cluster=autopilot-cluster'
       ]
  id: Deploy_to_GKE
  waitFor:
  - Push_Container
options:
  logging: CLOUD_LOGGING_ONLY
