version: '3.1'
services:
  # visualizer:
  #   build: ./visualizer
  #   ports:
  #     - 8082:8080
  #   environment:
  #     PROJECT_ID: "cloud-run-instances-demo"
  #     TOPIC_NAME: "hello-topic-local"
  #     GOOGLE_APPLICATION_CREDENTIALS: "/keys/hello-topic-subscriber-key.json"
  #   volumes:
  #     - /usr/local/google/home/manasakandula/demos/keys:/keys
      
  cymbalstore:
    build: ./webpage
    ports:
      - 8081:8080
    environment:
      PROJECT_ID: "k8s-demos-386513"
      TOPIC_NAME: "cymbal-topic-local"
      MESSAGE_INTERVAL: "2"
      GOOGLE_APPLICATION_CREDENTIALS: "/keys/k8s-demo-cloudbuild-key.json"
    volumes:
      - /usr/local/google/home/manasakandula/demos/keys:/keys